/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#222222",
        surface: "#1a1a1a",
        "on-background": "#ffffff",
        "on-secondary-fixed": "#111111",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        background: "#111111",
        "inverse-primary": "#B89761",
        "outline-variant": "#444444",
        outline: "#888888",
        "surface-container-low": "#151515",
        "on-secondary-fixed-variant": "#222222",
        "secondary-fixed": "#B89761",
        tertiary: "#111111",
        "primary-container": "#222222",
        "tertiary-fixed": "#2a2a2a",
        "on-tertiary-fixed-variant": "#aaaaaa",
        "inverse-on-surface": "#111111",
        "surface-tint": "#B89761",
        secondary: "#B89761",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#cccccc",
        "surface-container-lowest": "#000000",
        "secondary-fixed-dim": "#a88a53",
        "inverse-surface": "#f0f1f1",
        "primary-fixed-dim": "#a88a53",
        "on-secondary-container": "#B89761",
        "on-primary-fixed-variant": "#B89761",
        "on-error-container": "#ffdad6",
        "on-secondary": "#111111",
        "tertiary-container": "#333333",
        "surface-variant": "#222222",
        "tertiary-fixed-dim": "#1a1a1a",
        error: "#ba1a1a",
        "on-primary-fixed": "#111111",
        "on-primary-container": "#B89761",
        primary: "#111111",
        "surface-container": "#1a1a1a",
        "surface-container-highest": "#333333",
        "on-tertiary-container": "#cccccc",
        "error-container": "#93000a",
        "secondary-container": "#222222",
        "surface-container-high": "#2a2a2a",
        "primary-fixed": "#B89761",
        "on-tertiary-fixed": "#ffffff",
        "surface-dim": "#111111",
        "on-surface": "#ffffff",
        gold: "#B89761",
        "gold-dark": "#987a4a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "section-gap": "120px",
        "container-max": "1280px",
        gutter: "24px",
        "margin-desktop": "64px",
        unit: "8px",
      },
      fontFamily: {
        "headline-lg": ["Playfair Display"],
        button: ["Inter"],
        "label-caps": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "400" }],
        button: ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.15em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
