/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f9f9f9",
        surface: "#f9f9f9",
        "on-background": "#1a1c1c",
        "on-secondary-fixed": "#241a00",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        background: "#f9f9f9",
        "inverse-primary": "#c8c6c5",
        "outline-variant": "#c4c7c7",
        outline: "#747878",
        "surface-container-low": "#f3f3f4",
        "on-secondary-fixed-variant": "#574500",
        "secondary-fixed": "#ffe088",
        tertiary: "#000000",
        "primary-container": "#1B4D40",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary-fixed-variant": "#454747",
        "inverse-on-surface": "#f0f1f1",
        "surface-tint": "#5f5e5e",
        secondary: "#735c00",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#444748",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#e9c349",
        "inverse-surface": "#2f3131",
        "primary-fixed-dim": "#c8c6c5",
        "on-secondary-container": "#745c00",
        "on-primary-fixed-variant": "#474746",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "tertiary-container": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        error: "#ba1a1a",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-container": "#858383",
        primary: "#0D2E26",
        "surface-container": "#eeeeee",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary-container": "#838484",
        "error-container": "#ffdad6",
        "secondary-container": "#fed65b",
        "surface-container-high": "#e8e8e8",
        "primary-fixed": "#e5e2e1",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-dim": "#dadada",
        "on-surface": "#1a1c1c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "section-gap": "120px",
        "container-max": "1280px",
        gutter: "24px",
        "margin-desktop": "64px",
        unit: "8px",
      },
      fontFamily: {
        "headline-lg": ["Playfair Display"],
        button: ["Inter"],
        "label-caps": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "400" }],
        button: ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.15em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
